/**
 * Handover Order Screen Styles
 * Pixel-perfect styles matching Figma design
 */

import { StyleSheet } from 'react-native';
import { Theme } from '../constants/Theme';
import { scale, verticalScale } from '../utils/responsive';

const handoverOrderStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  content: {
    flex: 1,
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(20),
    paddingBottom: verticalScale(100),
    gap: scale(24),
  },
  customerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
    paddingHorizontal: scale(12),
    paddingVertical: scale(16),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    width: '100%',
  },
  customerAvatarContainer: {
    width: scale(56),
    height: scale(56),
    backgroundColor: 'rgba(35, 114, 39, 0.1)',
    borderRadius: scale(14),
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  customerAvatar: {
    width: scale(28),
    height: scale(28),
  },
  customerInfo: {
    flex: 1,
    gap: scale(4),
    marginRight: scale(8),
    minWidth: 0,
  },
  customerName: {
    fontSize: scale(15.75),
    lineHeight: scale(24.5),
    fontWeight: '700',
    color: '#101828',
  },
  customerPhone: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#4A5565',
  },
  callButton: {
    width: scale(42),
    height: scale(42),
    backgroundColor: Theme.colors.primaryMedium,
    borderRadius: scale(21),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#237227',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    flexShrink: 0, // Prevent button from shrinking
  },
  callButtonImage: {
    width: scale(17.5),
    height: scale(17.5),
  },
  otpSection: {
    gap: scale(16),
  },
  otpSectionHeader: {
    gap: scale(4),
  },
  otpTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: scale(12),
  },
  sendOtpButton: {
    paddingVertical: scale(6),
    paddingHorizontal: scale(10),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(10),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  /** Full-width primary action on OTP verification screen */
  otpPrimaryActionButton: {
    width: '100%',
    minHeight: scale(48),
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    backgroundColor: Theme.colors.primaryMedium,
    borderRadius: scale(12.75),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  otpScreenFooter: {
    flexShrink: 0,
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(12),
    backgroundColor: Theme.colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  sendOtpButtonText: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '700',
    color: '#0A0A0A',
  },
  otpSectionTitle: {
    fontSize: scale(15.75),
    lineHeight: scale(24.5),
    fontWeight: '700',
    color: '#101828',
  },
  otpSectionSubtitle: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#4A5565',
  },
  /** @deprecated Use OtpPinInput component (56×56 boxes). Kept for legacy references. */
  otpInputContainer: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    gap: scale(10.5),
    justifyContent: 'center',
  },
  otpInputBox: {
    width: scale(56),
    height: scale(56),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Theme.colors.white,
    borderRadius: scale(8),
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  otpInputBoxLast: {
    width: scale(56),
    height: scale(56),
  },
  otpInputBoxFocused: {
    borderColor: '#CEE3D7',
  },
  otpInputText: {
    fontSize: scale(20),
    lineHeight: scale(28),
    fontWeight: '700',
    color: '#101828',
    textAlign: 'center',
    padding: 0,
    margin: 0,
  },
  otpErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: scale(8),
    paddingLeft: scale(14),
    paddingRight: scale(0),
    paddingVertical: scale(0),
    backgroundColor: '#FEF2F2',
    borderRadius: scale(12.75),
    borderWidth: 1,
    borderColor: '#FFE2E2',
    height: scale(32),
  },
  otpErrorIcon: {
    width: scale(17.5),
    height: scale(17.5),
    backgroundColor: '#FB2C36',
    borderRadius: scale(8.75),
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: scale(0.015625),
  },
  otpErrorIconText: {
    fontSize: scale(12),
    lineHeight: scale(14),
    fontWeight: '700',
    color: Theme.colors.white,
    width: scale(8.58),
    height: scale(14),
  },
  otpErrorText: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#E7000B',
    width: scale(158.3),
    height: scale(17.5),
  },
  paymentSection: {
    gap: scale(10.5),
  },
  paymentSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: scale(107.34375),
  },
  paymentSectionTitle: {
    fontSize: scale(15.75),
    lineHeight: scale(24.5),
    fontWeight: '700',
    color: '#101828',
  },
  devToggleButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(12),
    paddingVertical: scale(3),
    paddingHorizontal: scale(8),
    backgroundColor: '#F3F4F6',
    borderRadius: scale(3.5),
    borderWidth: 1,
    borderColor: '#D1D5DC',
  },
  devToggleText: {
    fontSize: scale(12),
    lineHeight: scale(15),
    fontWeight: '400',
    color: '#4A5565',
  },
  paymentCard: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(16),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: scale(8),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  paymentPaidOnlyRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  paymentAmountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: scale(132.65625),
  },
  paymentAmountLeft: {
    gap: scale(4),
    width: scale(107.33),
  },
  paymentAmountLabel: {
    fontSize: scale(12),
    lineHeight: scale(14),
    fontWeight: '400',
    textTransform: 'uppercase',
    color: '#4A5565',
  },
  paymentAmountValue: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  paymentAmountText: {
    fontSize: scale(21),
    lineHeight: scale(28),
    fontWeight: '700',
    color: '#101828',
  },
  paymentStatusBadge: {
    paddingVertical: scale(3.5),
    paddingHorizontal: scale(10.5),
    borderRadius: scale(9999),
    minWidth: scale(70.02),
    height: scale(21),
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentStatusBadgePending: {
    backgroundColor: '#FFEDD4',
  },
  paymentStatusBadgePaid: {
    backgroundColor: 'rgba(35, 114, 39, 0.1)',
  },
  paymentStatusText: {
    fontSize: scale(12),
    lineHeight: scale(14),
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  paymentStatusTextPending: {
    color: '#F54900',
  },
  paymentStatusTextPaid: {
    color: '#237227',
  },
  paymentButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: scale(12),
  },
  showQRButton: {
    flex: 1,
    height: scale(42),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(8),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(12.75),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  showQRButtonText: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#0A0A0A',
  },
  cashCollectedButton: {
    flex: 1,
    height: scale(42),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(8),
    backgroundColor: Theme.colors.primaryMedium,
    borderRadius: scale(12.75),
  },
  cashCollectedButtonText: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '700',
    color: Theme.colors.white,
  },
  // Prepaid payment styles
  paymentPrepaidRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  paymentPrepaidLeft: {
    gap: scale(4),
  },
  paymentPrepaidLabel: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#4A5565',
  },
  paymentPrepaidValue: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  paymentPrepaidText: {
    fontSize: scale(14),
    lineHeight: scale(21),
    fontWeight: '700',
    color: '#101828',
  },
  paymentPrepaidStatusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  paymentPrepaidStatusLabel: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#4A5565',
  },
  paymentPrepaidStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    paddingVertical: 0,
    paddingHorizontal: scale(10.5),
    backgroundColor: 'rgba(35, 114, 39, 0.1)',
    borderRadius: scale(9999),
    height: scale(21),
  },
  paymentPrepaidStatusDot: {
    width: scale(7),
    height: scale(7),
    borderRadius: scale(3.5),
    backgroundColor: '#237227',
  },
  paymentPrepaidStatusText: {
    fontSize: scale(12),
    lineHeight: scale(14),
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: scale(0.25),
    color: '#237227',
  },
  deliveryProofSection: {
    gap: scale(8),
  },
  deliveryProofTitle: {
    fontSize: scale(15.75),
    lineHeight: scale(24.5),
    fontWeight: '700',
    color: '#101828',
  },
  deliveryProofCard: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(16),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(8),
    borderWidth: 2,
    borderColor: '#D1D5DC',
    borderStyle: 'dashed',
    minHeight: scale(142),
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(8),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  deliveryProofCardWithPhoto: {
    borderStyle: 'solid',
    borderColor: '#F3F4F6',
  },
  deliveryProofIcon: {
    width: scale(42),
    height: scale(42),
    backgroundColor: '#F3F4F6',
    borderRadius: scale(21),
    justifyContent: 'center',
    alignItems: 'center',
  },
  deliveryProofText: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#4A5565',
  },
  deliveryProofPhoto: {
    width: '100%',
    height: scale(112),
    borderRadius: scale(12.75),
    backgroundColor: '#E5E7EB',
  },
  itemsSection: {
    gap: scale(8),
  },
  itemsTitle: {
    fontSize: scale(15.75),
    lineHeight: scale(24.5),
    fontWeight: '700',
    color: '#101828',
  },
  itemsCard: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(16),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  orderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: scale(12),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  orderItemName: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#101828',
    flex: 1,
  },
  orderItemQuantity: {
    fontSize: scale(12.25),
    lineHeight: scale(17.5),
    fontWeight: '400',
    color: '#4A5565',
    textAlign: 'right',
  },
  orderItemSeparator: {
    height: 0,
  },
  bottomButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(20),
    paddingTop: verticalScale(12),
    backgroundColor: Theme.colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 5,
  },
  bottomButton: {
    width: '100%',
    height: scale(56),
    backgroundColor: Theme.colors.primaryMedium,
    borderRadius: scale(9999),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scale(8),
    position: 'relative',
    overflow: 'hidden',
  },
  bottomButtonDisabled: {
    opacity: 0.5,
  },
  bottomButtonLeftCircle: {
    position: 'absolute',
    left: 0,
    width: scale(56),
    height: scale(56),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: scale(28),
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomButtonText: {
    fontSize: scale(15.75),
    lineHeight: scale(24.5),
    fontWeight: '700',
    color: Theme.colors.white,
    opacity: 0.84,
  },
  bottomButtonRightIcon: {
    position: 'absolute',
    right: scale(3.5),
    width: scale(49),
    height: scale(49),
    backgroundColor: Theme.colors.white,
    borderRadius: scale(24.5),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 6,
  },
});

export default handoverOrderStyles;

